
#ifndef GENERICS_H
#define GENERICS_H
 #define GENERIC_TYPE_1
 #define GENERIC_TYPE_2
 #define GENERIC_TYPE_3
 #define GENERIC_TYPE_4
 #define GENERIC_TYPE_5
 #define GENERIC_TYPE_6
 #define GENERIC_TYPE_7
 #define GENERIC_TYPE_8
 #define GENERIC_TYPE_9
 #define GENERIC_TYPE_10
 #define GENERIC_TYPE_11
 #define GENERIC_TYPE_12
 #define GENERIC_TYPE_13
 #define GENERIC_TYPE_14
 #define GENERIC_TYPE_15
 #define GENERIC_TYPE_16
 #define GENERIC_TYPE_17
 #define GENERIC_TYPE_18
 #define GENERIC_TYPE_19
 #define GENERIC_TYPE_20
 #define GENERIC_TYPE_21
 #define GENERIC_TYPE_22
 #define GENERIC_TYPE_23
 #define GENERIC_TYPE_24
 #define GENERIC_TYPE_25
 #define GENERIC_TYPE_26
 #define GENERIC_TYPE_27
 #define GENERIC_TYPE_28
 #define GENERIC_TYPE_29
 #define GENERIC_TYPE_30
 #define GENERIC_TYPE_31
 #define GENERIC_TYPE_32
 #define GENERIC_TYPE_33
 #define GENERIC_TYPE_34
 #define GENERIC_TYPE_35
 #define GENERIC_TYPE_36
 #define GENERIC_TYPE_37
 #define GENERIC_TYPE_38
 #define GENERIC_TYPE_39
 #define GENERIC_TYPE_40
 #define GENERIC_TYPE_41
 #define GENERIC_TYPE_42
 #define GENERIC_TYPE_43
 #define GENERIC_TYPE_44
 #define GENERIC_TYPE_45
 #define GENERIC_TYPE_46
 #define GENERIC_TYPE_47
 #define GENERIC_TYPE_48
 #define GENERIC_TYPE_49
 #define GENERIC_TYPE_50
 #define GENERIC_TYPE_51
 #define GENERIC_TYPE_52
 #define GENERIC_TYPE_53
 #define GENERIC_TYPE_54
 #define GENERIC_TYPE_55
 #define GENERIC_TYPE_56
 #define GENERIC_TYPE_57
 #define GENERIC_TYPE_58
 #define GENERIC_TYPE_59
 #define GENERIC_TYPE_60
 #define GENERIC_TYPE_61
 #define GENERIC_TYPE_62
 #define GENERIC_TYPE_63
 #define GENERIC_TYPE_64
#endif //GENERICS_H
#define GENERIC_ELEMENT(type) type:#type,
#define GENERIC_NAME(val) \
_Generic((val), \
 GENERIC_TYPE_1 \
 GENERIC_TYPE_2 \
 GENERIC_TYPE_3 \
 GENERIC_TYPE_4 \
 GENERIC_TYPE_5 \
 GENERIC_TYPE_6 \
 GENERIC_TYPE_7 \
 GENERIC_TYPE_8 \
 GENERIC_TYPE_9 \
 GENERIC_TYPE_10 \
 GENERIC_TYPE_11 \
 GENERIC_TYPE_12 \
 GENERIC_TYPE_13 \
 GENERIC_TYPE_14 \
 GENERIC_TYPE_15 \
 GENERIC_TYPE_16 \
 GENERIC_TYPE_17 \
 GENERIC_TYPE_18 \
 GENERIC_TYPE_19 \
 GENERIC_TYPE_20 \
 GENERIC_TYPE_21 \
 GENERIC_TYPE_22 \
 GENERIC_TYPE_23 \
 GENERIC_TYPE_24 \
 GENERIC_TYPE_25 \
 GENERIC_TYPE_26 \
 GENERIC_TYPE_27 \
 GENERIC_TYPE_28 \
 GENERIC_TYPE_29 \
 GENERIC_TYPE_30 \
 GENERIC_TYPE_31 \
 GENERIC_TYPE_32 \
 GENERIC_TYPE_33 \
 GENERIC_TYPE_34 \
 GENERIC_TYPE_35 \
 GENERIC_TYPE_36 \
 GENERIC_TYPE_37 \
 GENERIC_TYPE_38 \
 GENERIC_TYPE_39 \
 GENERIC_TYPE_40 \
 GENERIC_TYPE_41 \
 GENERIC_TYPE_42 \
 GENERIC_TYPE_43 \
 GENERIC_TYPE_44 \
 GENERIC_TYPE_45 \
 GENERIC_TYPE_46 \
 GENERIC_TYPE_47 \
 GENERIC_TYPE_48 \
 GENERIC_TYPE_49 \
 GENERIC_TYPE_50 \
 GENERIC_TYPE_51 \
 GENERIC_TYPE_52 \
 GENERIC_TYPE_53 \
 GENERIC_TYPE_54 \
 GENERIC_TYPE_55 \
 GENERIC_TYPE_56 \
 GENERIC_TYPE_57 \
 GENERIC_TYPE_58 \
 GENERIC_TYPE_59 \
 GENERIC_TYPE_60 \
 GENERIC_TYPE_61 \
 GENERIC_TYPE_62 \
 GENERIC_TYPE_63 \
 GENERIC_TYPE_64 \
default:"")
#define EXPAND_(x) x
#define EXPAND(x) EXPAND_(x)
#if GENERIC_NAME_N == 0
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 1
 #elif GENERIC_NAME_N == 1
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 2
 #elif GENERIC_NAME_N == 2
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 3
 #elif GENERIC_NAME_N == 3
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 4
 #elif GENERIC_NAME_N == 4
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 5
 #elif GENERIC_NAME_N == 5
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 6
 #elif GENERIC_NAME_N == 6
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 7
 #elif GENERIC_NAME_N == 7
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 8
 #elif GENERIC_NAME_N == 8
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 9
 #elif GENERIC_NAME_N == 9
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 10
 #elif GENERIC_NAME_N == 10
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 11
 #elif GENERIC_NAME_N == 11
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 12
 #elif GENERIC_NAME_N == 12
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 13
 #elif GENERIC_NAME_N == 13
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 14
 #elif GENERIC_NAME_N == 14
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 15
 #elif GENERIC_NAME_N == 15
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 16
 #elif GENERIC_NAME_N == 16
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 17
 #elif GENERIC_NAME_N == 17
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 18
 #elif GENERIC_NAME_N == 18
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 19
 #elif GENERIC_NAME_N == 19
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 20
 #elif GENERIC_NAME_N == 20
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 21
 #elif GENERIC_NAME_N == 21
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 22
 #elif GENERIC_NAME_N == 22
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 23
 #elif GENERIC_NAME_N == 23
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 24
 #elif GENERIC_NAME_N == 24
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 25
 #elif GENERIC_NAME_N == 25
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 26
 #elif GENERIC_NAME_N == 26
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 27
 #elif GENERIC_NAME_N == 27
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 28
 #elif GENERIC_NAME_N == 28
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 29
 #elif GENERIC_NAME_N == 29
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 30
 #elif GENERIC_NAME_N == 30
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 31
 #elif GENERIC_NAME_N == 31
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 32
 #elif GENERIC_NAME_N == 32
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 33
 #elif GENERIC_NAME_N == 33
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 34
 #elif GENERIC_NAME_N == 34
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 35
 #elif GENERIC_NAME_N == 35
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 36
 #elif GENERIC_NAME_N == 36
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 37
 #elif GENERIC_NAME_N == 37
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 38
 #elif GENERIC_NAME_N == 38
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 39
 #elif GENERIC_NAME_N == 39
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 40
 #elif GENERIC_NAME_N == 40
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 41
 #elif GENERIC_NAME_N == 41
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 42
 #elif GENERIC_NAME_N == 42
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 43
 #elif GENERIC_NAME_N == 43
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 44
 #elif GENERIC_NAME_N == 44
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 45
 #elif GENERIC_NAME_N == 45
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 46
 #elif GENERIC_NAME_N == 46
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 47
 #elif GENERIC_NAME_N == 47
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 48
 #elif GENERIC_NAME_N == 48
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 49
 #elif GENERIC_NAME_N == 49
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 50
 #elif GENERIC_NAME_N == 50
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 51
 #elif GENERIC_NAME_N == 51
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 52
 #elif GENERIC_NAME_N == 52
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 53
 #elif GENERIC_NAME_N == 53
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 54
 #elif GENERIC_NAME_N == 54
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 55
 #elif GENERIC_NAME_N == 55
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 56
 #elif GENERIC_NAME_N == 56
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 57
 #elif GENERIC_NAME_N == 57
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 58
 #elif GENERIC_NAME_N == 58
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 59
 #elif GENERIC_NAME_N == 59
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 60
 #elif GENERIC_NAME_N == 60
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 61
 #elif GENERIC_NAME_N == 61
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 62
 #elif GENERIC_NAME_N == 62
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 63
 #elif GENERIC_NAME_N == 63
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 64
 #elif GENERIC_NAME_N == 64
 #undef GENERIC_NAME_N
 #define GENERIC_NAME_N 65
#endif
#if GENERIC_NAME_N == 1
#define GENERIC_TYPE_1 GENERIC_ELEMENT(_1_tn)
#elif GENERIC_NAME_N == 2
#define GENERIC_TYPE_2 GENERIC_ELEMENT(_2_tn)
#elif GENERIC_NAME_N == 3
#define GENERIC_TYPE_3 GENERIC_ELEMENT(_3_tn)
#elif GENERIC_NAME_N == 4
#define GENERIC_TYPE_4 GENERIC_ELEMENT(_4_tn)
#elif GENERIC_NAME_N == 5
#define GENERIC_TYPE_5 GENERIC_ELEMENT(_5_tn)
#elif GENERIC_NAME_N == 6
#define GENERIC_TYPE_6 GENERIC_ELEMENT(_6_tn)
#elif GENERIC_NAME_N == 7
#define GENERIC_TYPE_7 GENERIC_ELEMENT(_7_tn)
#elif GENERIC_NAME_N == 8
#define GENERIC_TYPE_8 GENERIC_ELEMENT(_8_tn)
#elif GENERIC_NAME_N == 9
#define GENERIC_TYPE_9 GENERIC_ELEMENT(_9_tn)
#elif GENERIC_NAME_N == 10
#define GENERIC_TYPE_10 GENERIC_ELEMENT(_10_tn)
#elif GENERIC_NAME_N == 11
#define GENERIC_TYPE_11 GENERIC_ELEMENT(_11_tn)
#elif GENERIC_NAME_N == 12
#define GENERIC_TYPE_12 GENERIC_ELEMENT(_12_tn)
#elif GENERIC_NAME_N == 13
#define GENERIC_TYPE_13 GENERIC_ELEMENT(_13_tn)
#elif GENERIC_NAME_N == 14
#define GENERIC_TYPE_14 GENERIC_ELEMENT(_14_tn)
#elif GENERIC_NAME_N == 15
#define GENERIC_TYPE_15 GENERIC_ELEMENT(_15_tn)
#elif GENERIC_NAME_N == 16
#define GENERIC_TYPE_16 GENERIC_ELEMENT(_16_tn)
#elif GENERIC_NAME_N == 17
#define GENERIC_TYPE_17 GENERIC_ELEMENT(_17_tn)
#elif GENERIC_NAME_N == 18
#define GENERIC_TYPE_18 GENERIC_ELEMENT(_18_tn)
#elif GENERIC_NAME_N == 19
#define GENERIC_TYPE_19 GENERIC_ELEMENT(_19_tn)
#elif GENERIC_NAME_N == 20
#define GENERIC_TYPE_20 GENERIC_ELEMENT(_20_tn)
#elif GENERIC_NAME_N == 21
#define GENERIC_TYPE_21 GENERIC_ELEMENT(_21_tn)
#elif GENERIC_NAME_N == 22
#define GENERIC_TYPE_22 GENERIC_ELEMENT(_22_tn)
#elif GENERIC_NAME_N == 23
#define GENERIC_TYPE_23 GENERIC_ELEMENT(_23_tn)
#elif GENERIC_NAME_N == 24
#define GENERIC_TYPE_24 GENERIC_ELEMENT(_24_tn)
#elif GENERIC_NAME_N == 25
#define GENERIC_TYPE_25 GENERIC_ELEMENT(_25_tn)
#elif GENERIC_NAME_N == 26
#define GENERIC_TYPE_26 GENERIC_ELEMENT(_26_tn)
#elif GENERIC_NAME_N == 27
#define GENERIC_TYPE_27 GENERIC_ELEMENT(_27_tn)
#elif GENERIC_NAME_N == 28
#define GENERIC_TYPE_28 GENERIC_ELEMENT(_28_tn)
#elif GENERIC_NAME_N == 29
#define GENERIC_TYPE_29 GENERIC_ELEMENT(_29_tn)
#elif GENERIC_NAME_N == 30
#define GENERIC_TYPE_30 GENERIC_ELEMENT(_30_tn)
#elif GENERIC_NAME_N == 31
#define GENERIC_TYPE_31 GENERIC_ELEMENT(_31_tn)
#elif GENERIC_NAME_N == 32
#define GENERIC_TYPE_32 GENERIC_ELEMENT(_32_tn)
#elif GENERIC_NAME_N == 33
#define GENERIC_TYPE_33 GENERIC_ELEMENT(_33_tn)
#elif GENERIC_NAME_N == 34
#define GENERIC_TYPE_34 GENERIC_ELEMENT(_34_tn)
#elif GENERIC_NAME_N == 35
#define GENERIC_TYPE_35 GENERIC_ELEMENT(_35_tn)
#elif GENERIC_NAME_N == 36
#define GENERIC_TYPE_36 GENERIC_ELEMENT(_36_tn)
#elif GENERIC_NAME_N == 37
#define GENERIC_TYPE_37 GENERIC_ELEMENT(_37_tn)
#elif GENERIC_NAME_N == 38
#define GENERIC_TYPE_38 GENERIC_ELEMENT(_38_tn)
#elif GENERIC_NAME_N == 39
#define GENERIC_TYPE_39 GENERIC_ELEMENT(_39_tn)
#elif GENERIC_NAME_N == 40
#define GENERIC_TYPE_40 GENERIC_ELEMENT(_40_tn)
#elif GENERIC_NAME_N == 41
#define GENERIC_TYPE_41 GENERIC_ELEMENT(_41_tn)
#elif GENERIC_NAME_N == 42
#define GENERIC_TYPE_42 GENERIC_ELEMENT(_42_tn)
#elif GENERIC_NAME_N == 43
#define GENERIC_TYPE_43 GENERIC_ELEMENT(_43_tn)
#elif GENERIC_NAME_N == 44
#define GENERIC_TYPE_44 GENERIC_ELEMENT(_44_tn)
#elif GENERIC_NAME_N == 45
#define GENERIC_TYPE_45 GENERIC_ELEMENT(_45_tn)
#elif GENERIC_NAME_N == 46
#define GENERIC_TYPE_46 GENERIC_ELEMENT(_46_tn)
#elif GENERIC_NAME_N == 47
#define GENERIC_TYPE_47 GENERIC_ELEMENT(_47_tn)
#elif GENERIC_NAME_N == 48
#define GENERIC_TYPE_48 GENERIC_ELEMENT(_48_tn)
#elif GENERIC_NAME_N == 49
#define GENERIC_TYPE_49 GENERIC_ELEMENT(_49_tn)
#elif GENERIC_NAME_N == 50
#define GENERIC_TYPE_50 GENERIC_ELEMENT(_50_tn)
#elif GENERIC_NAME_N == 51
#define GENERIC_TYPE_51 GENERIC_ELEMENT(_51_tn)
#elif GENERIC_NAME_N == 52
#define GENERIC_TYPE_52 GENERIC_ELEMENT(_52_tn)
#elif GENERIC_NAME_N == 53
#define GENERIC_TYPE_53 GENERIC_ELEMENT(_53_tn)
#elif GENERIC_NAME_N == 54
#define GENERIC_TYPE_54 GENERIC_ELEMENT(_54_tn)
#elif GENERIC_NAME_N == 55
#define GENERIC_TYPE_55 GENERIC_ELEMENT(_55_tn)
#elif GENERIC_NAME_N == 56
#define GENERIC_TYPE_56 GENERIC_ELEMENT(_56_tn)
#elif GENERIC_NAME_N == 57
#define GENERIC_TYPE_57 GENERIC_ELEMENT(_57_tn)
#elif GENERIC_NAME_N == 58
#define GENERIC_TYPE_58 GENERIC_ELEMENT(_58_tn)
#elif GENERIC_NAME_N == 59
#define GENERIC_TYPE_59 GENERIC_ELEMENT(_59_tn)
#elif GENERIC_NAME_N == 60
#define GENERIC_TYPE_60 GENERIC_ELEMENT(_60_tn)
#elif GENERIC_NAME_N == 61
#define GENERIC_TYPE_61 GENERIC_ELEMENT(_61_tn)
#elif GENERIC_NAME_N == 62
#define GENERIC_TYPE_62 GENERIC_ELEMENT(_62_tn)
#elif GENERIC_NAME_N == 63
#define GENERIC_TYPE_63 GENERIC_ELEMENT(_63_tn)
#elif GENERIC_NAME_N == 64
#define GENERIC_TYPE_64 GENERIC_ELEMENT(_64_tn)
#endif
#define GEN_CAT_(a, b) a##b
#define GEN_CAT(a, b) GEN_CAT_(a, b)
#define GEN_CAT_3(a,b,c) GEN_CAT(a,GEN_CAT(b,c))
#define STRINGIFY(x) #x
#define EXPAND_AND_STRINGIFY(x) STRINGIFY(x)
#define MAKE_NEW_TYPE_HELPER(type, newtype)\
typedef type newtype;\
REGISTER_ALIASED_PRINTER(type, newtype);
#define MAKE_NEW_TYPE(type)\
MAKE_NEW_TYPE_HELPER(type, GEN_CAT_3(_,GENERIC_NAME_N,_tn))
